import {
  BarChart,
  Bike,
  BookA,
  Bot,
  BotMessageSquare,
  Brain,
  BrainCog,
  Candy,
  CheckCircle,
  Chromium,
  Cloud,
  CloudCog,
  Cog,
  Cpu,
  Database,
  FileChartColumn,
  FileCheckCorner,
  FileCode,
  FileText,
  FileXCorner,
  Gamepad,
  GitBranch,
  Globe,
  Gpu,
  Hand,
  HardDrive,
  Image,
  Joystick,
  Layers,
  Link,
  Microchip,
  Monitor,
  MonitorCloud,
  ScreenShare,
  Server,
  Smartphone,
  SmartphoneCharging,
  TabletSmartphone,
} from "lucide-react";
import type { Type } from "./interfaces";

export const types: Type[] = [
  {
    title: "Software Development",
    desc: "Široka oblast koja obuhvata razvoj softvera za web, mobilne i desktop platforme; uključuje dizajn arhitekture, pisanje koda, testiranje i isporuku.",
    langs: ["zavisno od podtipa"],
    tools: ["IDE/CI/CD", "VCS (Git)", "build tools"],
    difficuly: "onako",
    icon: MonitorCloud,
    avgSalary: 150_000,
    demand: 5,
    subType: [
      {
        title: "Web Development",
        desc: "Razvoj aplikacija koje rade u browseru i/ili na web serverima.",
        langs: ["HTML", "CSS", "JavaScript", "Rust", "..."],
        tools: ["Set frontend alatki", "Set backend alatki"],
        difficuly: "lako",
        icon: Globe,
        avgSalary: 160_000,
        demand: 5,
        subType: [
          {
            title: "Frontend Development",
            desc: "Klijentska strana aplikacije: UI, UX i interakcija sa korisnikom.",
            langs: ["HTML", "CSS", "JavaScript"],
            tools: ["React", "Vue", "Svelte", "Tailwind", "Vite"],
            difficuly: "lako",
            icon: Layers,
            // Adorio median (frontend) -> 167,060 RSD neto
            avgSalary: 167_060,
            demand: 5,
          },
          {
            title: "Backend Development",
            desc: "Serverska logika, baze podataka, API-ji i arhitektura sistema.",
            langs: ["Java", "Node.js", "Python", "Rust", "SQL"],
            tools: [
              "Spring",
              ".NET",
              "Express",
              "Docker",
              "Kubernetes",
              "Postgres",
            ],
            difficuly: "tesko",
            icon: Server,
            // Adorio median (backend) -> 222,239 RSD neto
            avgSalary: 222_239,
            demand: 4,
          },
        ],
      },
      {
        title: "Mobile Development",
        desc: "Razvoj aplikacija za mobilne uređaje (Android/iOS).",
        langs: ["Kotlin", "Swift", "Java", "Dart", "JavaScript"],
        tools: ["Android SDK", "Xcode", "Flutter", "React Native"],
        difficuly: "onako",
        icon: Smartphone,
        avgSalary: 170_000,
        demand: 4,
        subType: [
          {
            title: "Native Mobile (Android / iOS)",
            desc: "Native aplikacije pisane za konkretnu platformu (Kotlin/Java za Android, Swift za iOS).",
            langs: ["Kotlin", "Java", "Swift"],
            tools: ["Android Studio", "Xcode"],
            difficuly: "tesko",
            icon: SmartphoneCharging,
            // Adorio median for Android ~187,803 RSD neto (used as native proxy)
            avgSalary: 187_803,
            demand: 4,
          },
          {
            title: "Cross-platform Mobile",
            desc: "Jedan kod-base za više platformi (npr. Flutter, React Native).",
            langs: ["Dart", "JavaScript"],
            tools: ["Flutter", "React Native", "Capacitor"],
            difficuly: "onako",
            icon: TabletSmartphone,
            // market medians and job posts cluster around ~110k–140k;
            // pragmatic typical = 125k RSD
            avgSalary: 125_000,
            demand: 3,
          },
        ],
      },
      {
        title: "Desktop Development",
        desc: "Aplikacije koje rade na desktop operativnim sistemima.",
        langs: ["C#", "C++", "Rust", "JavaScript", "Dart"],
        tools: [".NET / WPF", "Qt", "Electron", "Flutter (desktop)"],
        difficuly: "onako",
        icon: Monitor,
        avgSalary: 200_000,
        demand: 2,
        subType: [
          {
            title: "Native Desktop",
            desc: "Native desktop aplikacije (visoke performanse, često C++/C#/.NET/Qt).",
            langs: ["C++", "C#", "Rust"],
            tools: ["Qt", ".NET", "Win32 API", "GTK"],
            difficuly: "tesko",
            icon: ScreenShare,
            // use .NET programmer 80% midpoint (InfoPlate .NET range ~116,869–403,258)
            avgSalary: 260_000,
            demand: 2,
          },
          {
            title: "Electron / Web-based Desktop",
            desc: "Desktop aplikacije izgrađene pomoću web tehnologija (Electron, Tauri, neutralni frameworki).",
            langs: ["JavaScript", "HTML", "CSS", "Dart"],
            tools: ["Electron", "Tauri", "NW.js", "Flutter (desktop)"],
            difficuly: "onako",
            icon: Chromium,
            // typically similar to frontend / full-stack bands
            avgSalary: 140_000,
            demand: 2,
          },
        ],
      },
    ],
  },

  {
    title: "Artificial Intelligence (AI) Development",
    desc: "Razvoj sistema koji simuliraju ljudsku inteligenciju: učenje, donošenje odluka, prepoznavanje obrazaca i autonomno ponašanje.",
    langs: ["Python", "C++", "Java", "R"],
    tools: ["NumPy", "TensorFlow", "PyTorch", "OpenAI API", "Jupyter"],
    difficuly: "tesko",
    icon: Bot,
    avgSalary: 300_000,
    demand: 4,
    subType: [
      {
        title: "Machine Learning",
        desc: "Oblast AI koja omogućava sistemima da uče iz podataka bez eksplicitnog programiranja.",
        langs: ["Python", "R", "Julia"],
        tools: ["Scikit-learn", "TensorFlow", "PyTorch"],
        difficuly: "tesko",
        icon: FileChartColumn,
        avgSalary: 280_000,
        demand: 4,
        subType: [
          {
            title: "Supervised Learning",
            desc: "Učenje na osnovu označenih podataka.",
            langs: ["Python"],
            tools: ["Scikit-learn", "XGBoost"],
            difficuly: "onako",
            icon: FileCheckCorner,
            avgSalary: 260_000,
            demand: 3,
          },
          {
            title: "Unsupervised Learning",
            desc: "Pronalaženje obrazaca u neoznačenim podacima.",
            langs: ["Python"],
            tools: ["Scikit-learn", "Pandas"],
            difficuly: "tesko",
            icon: FileXCorner,
            avgSalary: 270_000,
            demand: 3,
          },
          {
            title: "Reinforcement Learning",
            desc: "Sistemi koji uče kroz interakciju sa okruženjem putem nagrada i kazni.",
            langs: ["Python", "C++"],
            tools: ["OpenAI Gym", "Stable Baselines"],
            difficuly: "tesko",
            icon: Candy,
            avgSalary: 300_000,
            demand: 2,
          },
        ],
      },

      {
        title: "Deep Learning",
        desc: "Napredna grana ML-a bazirana na neuronskim mrežama i velikim količinama podataka.",
        langs: ["Python"],
        tools: ["TensorFlow", "PyTorch", "Keras"],
        difficuly: "tesko",
        icon: Brain,
        avgSalary: 320_000,
        demand: 4,
        subType: [
          {
            title: "Neural Networks",
            desc: "Osnovna arhitektura dubokog učenja bazirana na slojevima neurona.",
            langs: ["Python"],
            tools: ["TensorFlow", "PyTorch"],
            difficuly: "tesko",
            icon: BrainCog,
            avgSalary: 310_000,
            demand: 3,
          },
          {
            title: "Generative AI",
            desc: "Kreiranje sadržaja: tekst, slike, audio, video pomoću AI modela.",
            langs: ["Python"],
            tools: ["OpenAI API", "Stable Diffusion", "HuggingFace"],
            difficuly: "onako",
            icon: FileText,
            avgSalary: 350_000,
            demand: 5,
          },
        ],
      },

      {
        title: "Natural Language Processing (NLP)",
        desc: "Obrada i razumevanje ljudskog jezika pomoću računara.",
        langs: ["Python"],
        tools: ["spaCy", "NLTK", "Transformers"],
        difficuly: "tesko",
        icon: BookA,
        avgSalary: 260_000,
        demand: 4,
      },

      {
        title: "Computer Vision",
        desc: "Analiza i obrada slika i video sadržaja pomoću AI sistema.",
        langs: ["Python", "C++"],
        tools: ["OpenCV", "YOLO", "TensorFlow"],
        difficuly: "tesko",
        icon: Image,
        avgSalary: 270_000,
        demand: 3,
      },

      {
        title: "AI Engineering (Production AI)",
        desc: "Implementacija AI modela u realne aplikacije i optimizacija performansi.",
        langs: ["Python", "Go"],
        tools: ["Docker", "FastAPI", "MLflow"],
        difficuly: "tesko",
        icon: BotMessageSquare,
        avgSalary: 320_000,
        demand: 4,
      },

      {
        title: "MLOps",
        desc: "Automatizacija treninga, deploya i monitoringa AI modela u produkciji.",
        langs: ["Python", "Bash"],
        tools: ["Kubeflow", "Docker", "Airflow", "DVC"],
        difficuly: "tesko",
        icon: Bike,
        avgSalary: 300_000,
        demand: 3,
      },

      {
        title: "Robotics AI",
        desc: "Primena AI u robotici i autonomnim sistemima.",
        langs: ["Python", "C++"],
        tools: ["ROS", "Gazebo", "TensorFlow"],
        difficuly: "tesko",
        icon: Bot,
        avgSalary: 260_000,
        demand: 1,
      },
    ],
  },
  {
    title: "System Programming",
    desc: "Grana programiranja fokusirana na razvoj operativnih sistema, drajvera, kernel modula i niskonivojskog softvera koji direktno komunicira sa hardverom.",
    langs: ["C", "C++", "Rust", "Assembly"],
    tools: ["GCC", "Clang", "GDB", "QEMU", "Linux Kernel", "Make", "CMake"],
    difficuly: "tesko",
    icon: Cpu,
    avgSalary: 180_000,
    demand: 3,
    subType: [
      {
        title: "Kernel Development",
        desc: "Razvoj i modifikacija jezgra operativnih sistema kao što su Linux, Windows ili BSD.",
        langs: ["C", "Rust", "Assembly"],
        tools: ["Linux Kernel Source", "GDB", "QEMU"],
        difficuly: "tesko",
        icon: Cog,
        avgSalary: 200_000,
        demand: 2,
      },
      {
        title: "Driver Development",
        desc: "Pisanje softvera koji omogućava komunikaciju između hardvera i operativnog sistema.",
        langs: ["C", "C++"],
        tools: ["Windows Driver Kit", "Linux Kernel Modules"],
        difficuly: "tesko",
        icon: HardDrive,
        avgSalary: 170_000,
        demand: 3,
      },
      {
        title: "Embedded Systems",
        desc: "Programiranje mikrokontrolera i sistema sa ograničenim resursima za rad u realnom vremenu.",
        langs: ["C", "C++", "Rust"],
        tools: ["Arduino", "STM32", "PlatformIO"],
        difficuly: "tesko",
        icon: Microchip,
        avgSalary: 160_000,
        demand: 4,
      },
    ],
  },
  {
    title: "Data Engineering & Analytics",
    desc: "Rad sa velikim količinama podataka, njihovo prikupljanje, obrada, analiza i vizualizacija za donošenje poslovnih odluka.",
    langs: ["Python", "SQL", "R"],
    tools: ["Pandas", "Apache Spark", "Power BI", "Tableau"],
    difficuly: "onako",
    icon: Database,
    avgSalary: 220_000,
    demand: 4,
    subType: [
      {
        title: "Data Analyst",
        desc: "Analiza i interpretacija podataka uz vizualne prikaze.",
        langs: ["Python", "SQL"],
        tools: ["Excel", "Power BI", "Tableau"],
        difficuly: "onako",
        icon: BarChart,
        avgSalary: 140_000,
        demand: 4,
      },
      {
        title: "Data Engineer",
        desc: "Izgradnja infrastrukture za obradu i skladištenje podataka.",
        langs: ["Python", "Scala", "SQL"],
        tools: ["Apache Spark", "Kafka", "Airflow"],
        difficuly: "tesko",
        icon: Server,
        // Adorio median (data engineer) -> 215,934 RSD neto
        avgSalary: 215_934,
        demand: 5,
      },
    ],
  },
  {
    title: "Game Development",
    desc: "Razvoj video igara za PC, konzole i mobilne uređaje.",
    langs: ["C#", "C++", "GDScript"],
    tools: ["Unity", "Unreal Engine", "Godot"],
    difficuly: "tesko",
    icon: Gamepad,
    // InfoPlate game developer midpoint
    avgSalary: 210_000,
    demand: 3,
    subType: [
      {
        title: "Game Programmer",
        desc: "Implementacija mehanika i sistema u igrama.",
        langs: ["C#", "C++"],
        tools: ["Unity", "Unreal"],
        difficuly: "tesko",
        icon: Joystick,
        avgSalary: 160_000,
        demand: 3,
      },
      {
        title: "Game Physics & Graphics",
        desc: "Optimizacija fizike, renderovanja i grafike.",
        langs: ["C++"],
        tools: ["Unreal Engine", "OpenGL"],
        difficuly: "tesko",
        icon: Gpu,
        avgSalary: 180_000,
        demand: 2,
      },
    ],
  },
  {
    title: "DevOps & Cloud",
    desc: "Automatizacija deploy procesa i upravljanje cloud infrastrukturom.",
    langs: ["Bash", "Python", "YAML"],
    tools: ["Docker", "Kubernetes", "AWS", "Terraform"],
    difficuly: "tesko",
    icon: Cloud,
    avgSalary: 220_000,
    demand: 5,
    subType: [
      {
        title: "Cloud Engineer",
        desc: "Rad sa cloud servisima i infrastrukturom.",
        langs: ["Python", "Go"],
        tools: ["AWS", "Azure", "GCP"],
        difficuly: "tesko",
        icon: CloudCog,
        avgSalary: 220_000,
        demand: 5,
      },
      {
        title: "CI/CD Engineer",
        desc: "Automatizacija build i deployment procesa.",
        langs: ["Bash"],
        tools: ["GitHub Actions", "Jenkins"],
        difficuly: "onako",
        icon: GitBranch,
        avgSalary: 190_000,
        demand: 4,
      },
    ],
  },
  {
    title: "Quality Assurance (QA)",
    desc: "Testiranje softvera radi osiguranja kvaliteta i stabilnosti.",
    langs: ["JavaScript", "Python"],
    tools: ["Selenium", "Cypress", "Playwright"],
    difficuly: "lako",
    icon: CheckCircle,
    avgSalary: 120_000,
    demand: 4,
    subType: [
      {
        title: "Manual Testing",
        desc: "Ručno testiranje aplikacija.",
        langs: [],
        tools: ["TestRail"],
        difficuly: "lako",
        icon: Hand,
        avgSalary: 90_000,
        demand: 3,
      },
      {
        title: "Automation Testing",
        desc: "Pisanje automatizovanih testova.",
        langs: ["JavaScript", "Python"],
        tools: ["Playwright", "Selenium"],
        difficuly: "onako",
        icon: Bot,
        avgSalary: 140_000,
        demand: 4,
      },
    ],
  },
  {
    title: "Blockchain Development",
    desc: "Razvoj decentralizovanih aplikacija i pametnih ugovora.",
    langs: ["Solidity", "JavaScript", "Rust"],
    tools: ["Ethereum", "Hardhat", "Web3.js"],
    difficuly: "tesko",
    icon: Link,
    // TalentUp reported median base ~2,588,700 RSD/year -> monthly ~215,725
    avgSalary: 215_725,
    demand: 3,
    subType: [
      {
        title: "Smart Contracts",
        desc: "Pisanje pametnih ugovora za blockchain mreže.",
        langs: ["Solidity"],
        tools: ["Remix", "Hardhat"],
        difficuly: "tesko",
        icon: FileCode,
        avgSalary: 240_000,
        demand: 3,
      },
    ],
  },
];
